tasks:
  - name: Configuring Wakatime
    init: |
      echo "[settings]" >> /home/gitpod/.wakatime.cfg
      echo "api_key = $WAKATIME_API_KEY" >> /home/gitpod/.wakatime.cfg
      bundle install
      
vscode:
  extensions:
    - streetsidesoftware.code-spell-checker-french
    - coenraads.bracket-pair-colorizer-2
    - streetsidesoftware.code-spell-checker
    - github.vscode-pull-request-github
    - eamodio.gitlens