image: wilda/gitpod-jekyll

tasks:
  - name: Init
    init: bundle install

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-french
    - eamodio.gitlens